### ISSUE TITLE
Need to be improve UI/UX design

### ISSUE THREAD

**Issue by Brijesh1963** [Architeuthis-Flux/Jumperless#11]
Ui/UX design is very basic level need to be improve this..
![Screenshot 2023-10-12 000637](https://github.com/Architeuthis-Flux/Jumperless/assets/98037970/c4a0b7bc-8700-4244-9541-98d475472337)

**Comment by Architeuthis-Flux** [comment]
You mean Tindie's UI? I don't really have any say in what they do, they're a marketplace where I sell these, but you're right, they could use a little improvement.

If you mean for the Jumperless itself, then yes, I'm working on it.
