### ISSUE TITLE
Getting a real USB vid/pid?

### ISSUE THREAD

**Issue by nilclass** [Architeuthis-Flux/Jumperless#17]
[Currently advertised USB IDs](https://github.com/Architeuthis-Flux/Jumperless/blob/bc217504b3e6a6739e501674906257f57e9cd681/JumperlessNano/src/main.cpp#L63) are fantasy values I assume :wink: 

The openmoko project has a proper Vendor ID and is handing out Product IDs to open source projects. The process is described here: http://wiki.openmoko.org/wiki/USB_Product_IDs - Pretty sure Jumperless meets the requirements!

**Comment by Architeuthis-Flux** [comment]
Oh good call, I just submitted [a pull request](https://github.com/pidcodes/pidcodes.github.com/pull/911) on pid.codes for their VID 0x1209 and my PID 0xACAB

I honestly can't believe that PID was available, ha.
