### ISSUE TITLE
Bug: In probe mode, selecting the 5v Nano pin connects to the 3v supply, not the 5v supply.

### ISSUE THREAD

**Issue by AdamSLevy** [Architeuthis-Flux/Jumperless#29]
Firmware: 1.3.3

steps:

1. enter probe mode either via the bridge app or connecting pin 19 and 18.
2. probe the 5v pin on the nano header, note that the bridge app will report that you have selected 3v.
3. probe another rail to connect it to what should be the nano's 5v output pin, but is 3v..
4. commit the connection (connect pins 18/19)
5. a volt meter will confirm that the connected rail has 3v, not 5v.

This behavior does not appear to be affected by the position of the voltage level switch.

**Comment by Architeuthis-Flux** [comment]
That _was_ intended behavior, because a digitalRead has no way of distinguishing 5V from 3V. But now that I'm using the ADCs to scan the board I can totally measure the analog voltage and do that. Thanks for the idea, I'll put it in the next release.
