### ISSUE TITLE
Python seems to not be able to access the programing port or the monitor port if its not manually defined in the project.

### ISSUE THREAD

**Issue by ericmoderbacher** [Architeuthis-Flux/Jumperless#5]
If the user comments out:
`upload_port = /dev/cu.usbmodem1101`
`monitor_port = /dev/cu.usbmodem1101`

it seems that the python can not access the automagically picked ports.  So we need to see if there is a way for python to get that for the user also automagically.

**Comment by Architeuthis-Flux** [comment]
Now that I've finally learned Python, I was able to fix this by having the extra_scripts.py search the serial ports for anything with "Jumperless" as the device descriptor and setting the upload and monitor ports to that. It also is in the Wokwi Bridge app so you don't need to manually select the port anymore.

So yeah, fixed.
