### ISSUE TITLE
Python user interface for setting the wokwi url is a bit broken

### ISSUE THREAD

**Issue by ericmoderbacher** [Architeuthis-Flux/Jumperless#6]
<img width="563" alt="Screenshot 2023-07-01 at 8 50 01 PM" src="https://github.com/Architeuthis-Flux/Jumperless/assets/8312116/0e6ec983-dce8-4a45-9969-b1f09f503de6">

Looks like the indexing of that menu is a bit broken.

**Comment by Architeuthis-Flux** [comment]
This should be fixed now in the new app. But if it still happens let me know.
